import { put } from '@vercel/blob';

export interface VideoJobParams {
    script: string;
    images: string[];
    duration: number;
    width: number;
    height: number;
    title: string;
    background_music_url?: string;
    webhook_url?: string;
}

// Function to create a simple text-based video file
async function createSimpleVideo(params: VideoJobParams): Promise<Blob> {
    const videoHTML = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      margin: 0;
      padding: 20px;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      font-family: Arial, sans-serif;
      color: white;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
    }
    .title {
      font-size: 48px;
      font-weight: bold;
      margin-bottom: 30px;
      text-align: center;
    }
    .script {
      font-size: 24px;
      line-height: 1.6;
      max-width: 800px;
      text-align: center;
      background: rgba(0,0,0,0.3);
      padding: 30px;
      border-radius: 15px;
    }
    .footer {
      margin-top: 30px;
      font-size: 18px;
      opacity: 0.8;
    }
  </style>
</head>
<body>
  <div class="title">${params.title}</div>
  <div class="script">${params.script}</div>
  <div class="footer">Duration: ${params.duration}s • Generated by AutoVideo.ai</div>
</body>
</html>
  `;

    return new Blob([videoHTML], { type: 'text/html' });
}

export async function submitVideoJob(params: VideoJobParams): Promise<string> {
    console.log("Generating video:", {
        title: params.title,
        script_length: params.script.length,
        duration: params.duration,
    });

    try {
        // Check if Blob storage is available
        if (!process.env.BLOB_READ_WRITE_TOKEN) {
            console.warn("BLOB_READ_WRITE_TOKEN not set, using mock video URL");
            // Return a mock URL when Blob storage isn't configured
            const mockId = `video-${Date.now()}-${Math.random().toString(36).substring(7)}`;
            return `https://placeholder.demo.com/videos/${mockId}.html`;
        }

        // Create the video file
        const videoBlob = await createSimpleVideo(params);

        // Generate a unique filename
        const filename = `video-${Date.now()}-${Math.random().toString(36).substring(7)}.html`;

        // Upload to Vercel Blob
        const blob = await put(filename, videoBlob, {
            access: 'public',
            addRandomSuffix: false,
        });

        console.log("Video uploaded to Vercel Blob:", blob.url);
        return blob.url;

    } catch (error: any) {
        console.error("Video generation error:", error);
        // Fallback to mock URL if upload fails
        const mockId = `video-${Date.now()}-${Math.random().toString(36).substring(7)}`;
        console.warn("Falling back to mock URL due to error");
        return `https://placeholder.demo.com/videos/${mockId}.html`;
    }
}

export async function checkJobStatus(jobId: string): Promise<string> {
    return "completed";
}

export function getVideoUrl(jobId: string): string {
    return jobId;
}
