import { put } from '@vercel/blob';

export interface VideoJobParams {
    script: string;
    images: string[];
    duration: number;
    width: number;
    height: number;
    title: string;
    background_music_url?: string;
    webhook_url?: string;
}

// Function to create a simple text-based MP4 video
// For now, we'll create a simple JSON file as a placeholder
// In production, this would use FFmpeg or a video API service
async function createSimpleVideo(params: VideoJobParams): Promise<Blob> {
    // Create a simple HTML-based video representation
    // This is a placeholder - in production you'd use proper video generation
    const videoHTML = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body {
      margin: 0;
      padding: 20px;
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      font-family: Arial, sans-serif;
      color: white;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
    }
    .title {
      font-size: 48px;
      font-weight: bold;
      margin-bottom: 30px;
      text-align: center;
    }
    .script {
      font-size: 24px;
      line-height: 1.6;
      max-width: 800px;
      text-align: center;
      background: rgba(0,0,0,0.3);
      padding: 30px;
      border-radius: 15px;
    }
    .footer {
      margin-top: 30px;
      font-size: 18px;
      opacity: 0.8;
    }
  </style>
</head>
<body>
  <div class="title">${params.title}</div>
  <div class="script">${params.script}</div>
  <div class="footer">Duration: ${params.duration}s • Generated by AutoVideo.ai</div>
</body>
</html>
  `;

    // Convert to blob
    return new Blob([videoHTML], { type: 'text/html' });
}

export async function submitVideoJob(params: VideoJobParams): Promise<string> {
    console.log("Generating video with Vercel Blob:", {
        title: params.title,
        script_length: params.script.length,
        duration: params.duration,
        dimensions: `${params.width}x${params.height}`
    });

    try {
        // Create a simple video file
        const videoBlob = await createSimpleVideo(params);

        // Generate a unique filename
        const filename = `video-${Date.now()}-${Math.random().toString(36).substring(7)}.html`;

        // Upload to Vercel Blob
        const blob = await put(filename, videoBlob, {
            access: 'public',
            addRandomSuffix: false,
        });

        console.log("Video uploaded to Vercel Blob:", blob.url);

        // Return the URL (which acts as our "job ID" and download URL)
        return blob.url;

    } catch (error: any) {
        console.error("Failed to upload video to Vercel Blob:", error);
        throw new Error(`Video upload failed: ${error.message}`);
    }
}

export async function checkJobStatus(jobId: string): Promise<string> {
    // Since we upload directly, the video is always "completed"
    return "completed";
}

export function getVideoUrl(jobId: string): string {
    // The jobId IS the video URL when using Vercel Blob
    return jobId;
}
